### ISSUE TITLE
How to do int8 inference

### ISSUE THREAD

**Issue by wujjun** [noahmr/yolov5-tensorrt#3]
I want to use yolov5 on TX2 using int8, how can I do it？

**Comment by noahmr** [comment]
Hi @wujjun, at the moment INT8 inference is not supported, only FP16 and FP32. I recognize that this may be a very useful feature, but haven't had the time to implement it.

You could try introducing the functionality yourself, the place to implement it would be in the ```Builder``` class of the library, setting the correct flags, implementing the calibrator etc. (see [here](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#optimizing_int8_c)). I'd of course be happy to receive contributions for this feature.
