### ISSUE TITLE
How to get bounding box coordinates and set maximum detection?

### ISSUE THREAD

**Issue by beatmonster** [noahmr/yolov5-tensorrt#4]
Hi, i'm currently building a project for detecting ball with real time object detection on jetson platform. The code i'm currently using is the process_live.py and it works perfectly fine but i need the bounding box coordinates and set the maximum detection to only detect 1 ball, can you help me with that? Thanks

**Comment by noahmr** [comment]
Hi @beatmonster, that's awesome! Is this by any chance a RoboCup project ? :))

In the process_live.py example, the place to get the bounding box coordinates would be [here](https://github.com/noahmr/yolov5-tensorrt/blob/6af93611fa275b4a4ff09a4c1fdbe717b433e4a1/examples/live/process_live.py#L112):
```python
for d in detections:
    yolov5tensorrt.visualizeDetection(d, image, magenta, 1.0)
```
All of the detected objects are placed within the 'detections' list. These are of the type 'Detection', which exposes a couple of variables and methods. The one to use here is 'boundingBox', which is gives a tuple (x, y, width, height) containing the coordinates you're looking for. As for limiting it to only 1 detection, you'd probably want to go through the list of detections and pick the object with the highest confidence (which can be accessed through 'score').

If you use the Python 'help' functionality, you can get some more info on all of the Python classes, although at the moment the Python documentation is not quite as good as the C++ documentation.

Feel free to ask if you have any more questions

**Comment by beatmonster** [comment]
No, its actually my assignment XD. 
Ok, i tried to use the 'boundingBox' but it returns the value of (0,0,0,0). As you can see below is my code:
![image](https://user-images.githubusercontent.com/102377016/165306099-6edddbd7-f9a0-4130-a302-df6486603622.png)
Am i doing it wrong?

**Comment by noahmr** [comment]
Currently you're creating a new Detection object every time, and retrieving the bounding box of that (which is initialized at 0,0,0,0). What you want is to use the Detections produced by the model, which is 'd' in the for-loop. In terms of code, it would look like this:
```Python
for d in detections:
    yolov5tensorrt.visualizeDetection(d, image, magenta, 1.0)
    print(d.boundingBox())
```

Good luck with your assignment, and feel free to reach out if you have more questions

**Comment by beatmonster** [comment]
It works now, thank you very much 😄
